
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import baseSize  from "./utils/document/resize";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/HeaderNav";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(baseSize);
  
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Header></Header>
        <main className="text-[16rem]">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
