
import "./globals.css";
import Footer from "./components/Footer/Footer";
import HeaderNav from "./components/Header/HeaderNav";
import type { Metadata } from "next";
import { useEffect, useState } from 'react';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderNav></HeaderNav>
        <main className="text-[16rem]">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
